name: build_and_push_to_manifest
on:
  push:
    branches:
      - '*'
    # tags:
    #   - '*.*.*'
  pull_request:
  workflow_dispatch:
env:
  GITLAB_REGISTRY: registry.gitlab.com/target-digital-transformation/devops

jobs:
  push_to_manifest:
    runs-on: ubuntu-latest
    name: push to manifest
    if: ${{ github.ref != 'tag' }}
    steps:

      - name: Checkout manifest repo
        uses: actions/checkout@v2
        with:
          repository: tespkg/tes_manifests
          token: ${{ secrets.TES_MANIFEST_TOKEN }}

      - name: Push to dev
        ## your main branch
        ## push the image name to env-dev/${{ github.repository }}
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: tespkg/action@deploy_to_dev
        with:
          ALIAS_GITHUB_REPOSITORY: tespkg/meera-centrum-meera-gpt
          TES_ENV: dev